def clients = ['user', 'pet']
def groups = ['smoke', 'regression']
properties([parameters([choice(choices: clients, description: 'Run on specific device', name: 'CLIENT'),
                        choice(choices: groups, description: 'Run specific group of tests', name: 'TEST_GROUP')]
                        )])
// filter clients
if ("${CLIENT}" == "all") {
    // remove every occurrence of <all>
    clients -= "all"
} else {
    clients = ["${CLIENT}"]
}

// main task
for(int i = 0; i < clients.size(); i++) {
    def client = clients[i]
    tasks["${clients}"] = {
        node {
             stage ("Execute tests for ${client}") {
                catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                    sh "./mvn clean test -Dclient=${client} -DincludeGroups=${TEST_GROUP}\""

                }
            }
            stage ("Aggregate reports for ${client}") {
                sh "allure generate allure-results --clean -o allure-report"
            }
            stage ("Publish HTML report for ${client}") {
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true,
                             reportDir: 'build/reports/allure-report', reportFiles: 'index.html',
                             reportName: "TestReport_${client}", reportTitles: "Test report for ${client}"])
            }

        }
    }
}

